import {  VerticalBox,HorizontalBox  } from "std-widgets.slint";
import {  ToggleSwitch } from "toggle_switch.slint";
import "../DouyinSansBold.subset.ttf";

export component AppWindow inherits Window {
    no-frame:true;
    width: 800px;
    // background : #00000000;
    in-out property<brush> my-background<=>self.background;
    in-out property<bool> on-top<=>self.always-on-top;
    in-out property<string> times: "2023-08-12 00:00:00";
    in-out property<bool> toggle-switch-sec-checked <=> toggle_switch_sec.checked;
    in-out property<bool> toggle-switch-transparent-checked <=> toggle_switch_transparent.checked;
    in-out property<bool> toggle-switch-on-top-checked <=> toggle_switch_on_top.checked;


    callback toggle-switch-sec-toggled<=>toggle_switch_sec.toggled;
    callback toggle-switch-on-top-toggled<=>toggle_switch_on_top.toggled;

    // 是否按下了鼠标
    property <bool> drag-area-pressed: false;
    // 记录按下的位置
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    // 调用Rust代码移动窗口
    callback move-window(length, length);

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
      
        moved => {
            //根据移动的偏移量，设置窗口位置
            move-window(self.mouse-x - drag-area-down-x, self.mouse-y - drag-area-down-y);
        }
        pointer-event(ev) => {
            drag-area-pressed = ev.kind == PointerEventKind.down;
            drag-area-down-x = self.mouse-x;
            drag-area-down-y = self.mouse-y;
        }
  }

    VerticalBox {
         Text {
            text: " \{root.times}";
            font-size: 80px;
            color: white;
         }

         HorizontalLayout {
                  // 这个元素会占据所有可用的额外空间
                Rectangle {
                    horizontal-stretch: 10;
                }
                Text {
                    font-family: "Douyin Sans";
                    text: "显示秒：";
                    color: white;
                }
            toggle_switch_sec := ToggleSwitch{
                horizontal-stretch: 1;
            }
            Text {
                font-family: "Douyin Sans";
                text: "置顶：";
                color: white;
            }
            toggle_switch_on_top := ToggleSwitch{
                horizontal-stretch: 1;
            }
            Text {
                font-family: "Douyin Sans";
                text: "背景透明：";
                color: white;
            }
            toggle_switch_transparent := ToggleSwitch{
                horizontal-stretch: 1;
                Text {
                    text: "zj";
                    font-size: 10px;
                    padding-right: 50px;
                    color: white;
                }
            }

         }

    }

}
